Merge upstream (#56)
* Remove extra word in heredoc documentation

From Thibault Jouan

Fixes [Misc #17872]

* * 2021-05-21 [ci skip]

* [DOC] Moved `File.fnmatch?` to dir.rb

So that no longer disturbed by C comment delimiters.

* Remove short options with argument [Bug #17870]

Remove GNU make `-O` and `-W` options which are short but followed
by an argument, so that `$mflags.set?(?n)` does not return `true`
wrongly.

* [ruby/rdoc] Use File.open to fix the OS Command Injection vulnerability in CVE-2021-31799

https://github.com/ruby/rdoc/commit/a7f5d6ab88

* [ruby/rdoc] Version 6.3.1

https://github.com/ruby/rdoc/commit/9307f932b7

* [ruby/rdoc] Update rdoc.gemspec by adding lib/rdoc/markup/table.rb

Fixes ruby/rdoc#808

https://github.com/ruby/rdoc/commit/80766fd389

* [ruby/rdoc] Dir.children is 2.5+

RDoc seems still supporting outdated 2.4.

https://github.com/ruby/rdoc/runs/2565344070?check_suite_focus=true#step:5:64
```
Error: test_remove_unparseable_CVE_2021_31799(TestRDocRDoc): NoMethodError: undefined method `children' for Dir:Class
/home/runner/work/rdoc/rdoc/test/rdoc/test_rdoc_rdoc.rb:467:in `block in test_remove_unparseable_CVE_2021_31799'
     464:       end
     465:
     466:       assert_equal file_list, @rdoc.remove_unparseable(file_list)
  => 467:       assert_equal file_list, Dir.children('.')
     468:     end
     469:   end
     470:
```

https://github.com/ruby/rdoc/commit/5a4a64dc0f

* [ruby/rdoc] Vertical-bar is disallowed in path names on Windows

No risk of remote code execution, when the file cannot be created.

https://github.com/ruby/rdoc/runs/2565343916?check_suite_focus=true#step:5:58
```
Error: test_remove_unparseable_CVE_2021_31799(TestRDocRDoc): Errno::EINVAL: Invalid argument @ utime_failed - | touch evil.txt && echo tags
D:/rubyinstaller-head-x64/lib/ruby/3.1.0/fileutils.rb:1142:in `utime'
D:/rubyinstaller-head-x64/lib/ruby/3.1.0/fileutils.rb:1142:in `block in touch'
D:/rubyinstaller-head-x64/lib/ruby/3.1.0/fileutils.rb:1139:in `each'
D:/rubyinstaller-head-x64/lib/ruby/3.1.0/fileutils.rb:1139:in `touch'
D:/a/rdoc/rdoc/test/rdoc/test_rdoc_rdoc.rb:463:in `block (2 levels) in test_remove_unparseable_CVE_2021_31799'
     460:     temp_dir do
     461:       file_list = ['| touch evil.txt && echo tags']
     462:       file_list.each do |f|
  => 463:         FileUtils.touch f
     464:       end
     465:
     466:       assert_equal file_list, @rdoc.remove_unparseable(file_list)
```

https://github.com/ruby/rdoc/commit/a7df7dc8fa

* [ruby/rdoc] Follow-up rubygems

Use test-unit assertions instead of minitest.

https://github.com/ruby/rdoc/commit/d6a6209d7f

* [ruby/rdoc] Drop support for Ruby 2.4

https://github.com/ruby/rdoc/commit/f480b970cc

* simple rescue+while+break should not use `throw`

609de71f043e8ba34f22b9993e444e2e5bb05709 fixes the issue by using
`throw` insn if `ensure` is used. However, that patch introduce
additional `throw` even if it is not needed. This patch solves
the issue.

This issue is pointed by @mame.

* Get rid of sporadic WSAEACCES on Windows [ruby-dev:42661]

* ripper: assertions for rescue/ensure in method body

* ripper: wrap endless method in bodystmt [Bug #17869]

* Avoid setting the visibility of refinement method entries

Since refinement search is always performed, these entries should always
be public. The method entry that the refinement search returns decides
the visibility.

Fixes [Bug #17822]

* * 2021-05-22 [ci skip]

* Build CDHASH properly when loading iseq from binary

Before this change, CDHASH operands were built as plain hashes when
loaded from binary. Without setting up the hash with the correct
st_table type, the hash can sometimes be an ar_table. When the hash is
an ar_table, lookups can call the `eql?` method on keys of the hash,
which makes the `opt_case_dispatch` instruction not "leaf" as it
implicitly declares.

The following script trips the stack canary for checking the leaf
attribute for `opt_case_dispatch` on VM_CHECK_MODE > 0 (enabled by
default with RUBY_DEBUG).

    rb_vm_iseq = RubyVM::InstructionSequence

    iseq = rb_vm_iseq.compile(<<-EOF)
      case Class.new(String).new("foo")
      when "foo"
        42
      end
    EOF

    puts rb_vm_iseq.load_from_binary(iseq.to_binary).eval

This commit changes the binary loading logic to build CDHASH with the
right st_table type. The dumping logic and the dump format stays the
same

* Do not allow array modifications after freeze inside sort!

If freezing an array inside sort!, previously the array could be
modified after the freeze.  This checks whether the receiver is
frozen after every yield and potential call to #> or #<,
preventing modifications if the receiver is frozen inside the
block or by the #> or #< call.

Fixes [Bug #17739]

* Refined portability of test for [Bug #17739]

The order of arguments to callback of qsort is not defined.
That means `a` may not be 3 at all.

* Update a comment about what 'inline' attr means

* Show a backtrace when tool/extlibs.rb fails

I'd like to retry this kind of error, but showing no backtrace is hard
to deal with.
https://github.com/ruby/ruby/runs/2644908002

* Use YAML.safe_load to use the permitted_classes option

* Refactor num_zero_p function (#4522)

* * 2021-05-24 [ci skip]

* [ruby/irb] respect NO_COLOR environment variable

When `NO_COLOR` is set to any non-nil value, output is not colorized.

See https://no-color.org/

https://github.com/ruby/irb/commit/401d0916fe

* [ruby/irb] update test/irb/test_init.rb to avoid useless eval

Co-authored-by: Nobuyoshi Nakada <nobu@ruby-lang.org>

https://github.com/ruby/irb/commit/2dfdc031ec

* Set USE_COLORIZE to the default value in a test

* xibbar is retired from cgi.rb maintainer

* add rb_id2str to lldb debugging scripts

* * 2021-05-25 [ci skip]

* Removed tracer from ruby repo

* Removed dbm from ruby repo

* Revert "Remove .travis.yml" to revive Travis.

This reverts commit 6b978d542704a5614af5e9375c4b31b8d2618652.

* .travis.yml: Ubuntu 20.04 Focal Fossa

This is a LTS.  Must be better than Xenial.

* .travis.yml: Update to use arm64/ppc64le/s390x.

* Use only the free pipelines arm64/ppc64le/s390x without credits on Travis.
  See <https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution>.
* Add ppc64le case.
* Update the gcc to gcc-11.
* Remove unused logic.
* Add the `tool/travis_wait.sh` to avoid a command timeout.
* Run the tests skipping some failing tests.
  * Set `TEST_ALL_SKIPPED_TESTS` env to skip the tests.
  * Run the tests separately returning ok status.
    The tests are executed if `TEST_ALL_SKIPPED_TESTS` env is set or
    `TEST_ALL_SEPARATED_TESTS` env is set.
  * Add `tool/ci_functions.sh` to manage the functions used in CI.
* Add arm64 to allow_failures due to the following issue.
  An arm64 job sometimes does not start right now.
  https://travis-ci.community/t/11629

* bootstraptest/test_ractor.rb: Skip an assertion on Travis arm64.

Skip the assertion to test the `Ractor.select` from multiple ractors that rarely
fails on Travis arm64.
See <https://bugs.ruby-lang.org/issues/17878>.

* Removed gdbm from ruby repo

* Update the latest list of default gems for misc/expand_tabs.rb

* Add Travis badge image to `README.md`. [ci skip] (#4527)

Align the order of the badges with ones on the wiki page.
https://bugs.ruby-lang.org/projects/ruby/wiki/CIServers

* Disable compaction on platforms that can't support it

Manual compaction also requires a read barrier, so we need to disable
even manual compaction on platforms that don't support mprotect.

[Bug #17871]

* * 2021-05-26 [ci skip]

* Ignore lib/irb/ext/tracer.rb with TestRequireLib because tracer library was removed from ruby repo

* RSS library is the bundled gems now

* Add Thread#native_thread_id [Feature #17853]

* Add NEWS about 46655156dcc37509dcb69fcd0717c110eb1c624a

* Add Thread#native_thread_id [Feature #17853]

* Suppress debug message

* Rescue NotImplementedError for a test of Thread#native_thread_id

http://rubyci.s3.amazonaws.com/solaris10-gcc/ruby-master/log/20210526T070003Z.fail.html.gz
```
  1) Error:
TestThread#test_thread_native_thread_id:
NotImplementedError: native_thread_id() function is unimplemented on this machine
    /export/home/users/chkbuild/cb-gcc/tmp/build/20210526T070003Z/ruby/test/ruby/test_thread.rb:1338:in `native_thread_id'
    /export/home/users/chkbuild/cb-gcc/tmp/build/20210526T070003Z/ruby/test/ruby/test_thread.rb:1338:in `test_thread_native_thread_id'
```

* .travis.yml: Remove skipped tests on ppc64le.

It was fixed at fc832ffbfaf581ff63ef40dc3f4ec5c8ff39aae6 .

* Fill out switch statement in push_mark_stack

When objects are popped from the mark stack, we check that the object is
the right type (otherwise an rb_bug happens).  The problem is that when
we pop a bad object from the stack, we have no idea what pushed the bad
object on the stack.

This change makes an error happen when a bad object is pushed on the
mark stack, that way we can track down the source of the bug.

Co-authored-by: Jeremy Evans <code@jeremyevans.net>
Co-authored-by: git <svn-admin@ruby-lang.org>
Co-authored-by: Nobuyoshi Nakada <nobu@ruby-lang.org>
Co-authored-by: aycabta <aycabta@gmail.com>
Co-authored-by: Yusuke Endoh <mame@ruby-lang.org>
Co-authored-by: Koichi Sasada <ko1@atdot.net>
Co-authored-by: Alan Wu <XrXr@users.noreply.github.com>
Co-authored-by: Takashi Kokubun <takashikkbn@gmail.com>
Co-authored-by: S.H <gamelinks007@gmail.com>
Co-authored-by: Mark Delk <jethrodaniel@gmail.com>
Co-authored-by: Hiroshi SHIBATA <hsbt@ruby-lang.org>
Co-authored-by: Aaron Patterson <tenderlove@ruby-lang.org>
Co-authored-by: Jun Aruga <jaruga@redhat.com>
Co-authored-by: 卜部昌平 <shyouhei@ruby-lang.org>
Co-authored-by: Jun Aruga <junaruga@users.noreply.github.com>
Co-authored-by: NARUSE, Yui <naruse@airemix.jp>